Add abort to git

diff --git a/git b/git
--- a/git
+++ b/git
@@ -1,5 +1,8 @@
 #!/bin/bash
 
-echo oops-from-git
-echo ARGS="$@"
-exit 46
+echo "$0: oops-from-git"
+echo "$0: ARGS=$@"
+echo "$0: aborting"
+kill -ABRT $$
+# exit is ignored in calling context
+# exit 46
